### ISSUE TITLE
easy way to implement scrolling?

### ISSUE THREAD

**Issue by Mis012** [actsl/kiss_sdl#16]
Hello,
I am in a need of a "widget" (editing the window widget would suffice), that would be able to let it's content be bigger than what fits on the screen, and upon swipe (it's meant for android) would scroll to reveal the content.
The problem is, the content will be multiple widgets, which can be clicked, and I need smooth scrolling while still being able to properly execute events on the widget I click, and of course only on that one.
For drawing, I'm using https://github.com/memononen/nanovg/ , so I suppose I'll have to figure that out separately.
Is there a recommended way to do this?
Thanks in advance :)

**Comment by actsl** [comment]
Hello,

This certainly can be done, using scrollbars, changing the widgets coordinates, and drawing only these widgets that are visible.

But you said smoothly, by default kiss_sdl doesn't support drawing widgets partially. It is a minimalist GUI toolkit. It can be changed to do that though, which may be quite interesting project, and not very difficult.
