### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by shuttersparks** [actsl/kiss_sdl#6]
Just starting into the code so I understand it. I like it! I need to create a number of custom widgets for process control displays and this looks like a good basis to start with.

Anyway, on Line 515 of kiss_widgets.c there appears to be a typo in the function name:

int kiss_p[r]ogressbar_draw(...

/phil

**Comment by actsl** [comment]
Right, this is a typo, thanks for finding it.

This, however, caused no problems whatsoever, because it was kiss_pogressbar_draw() everywhere that it appeared. Because i used to copy the function names and not write them manually.

This typo is now fixed in the new release, version 1.0.0 .
